"""add reel_types_pref to users

Revision ID: 47ca30197259
Revises: b0d35c2ba291
Create Date: 2026-02-28 18:24:09.549515
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '47ca30197259'
down_revision: Union[str, None] = 'b0d35c2ba291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reel_types_pref', sa.JSON(), server_default='["clips"]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reel_types_pref')
    # ### end Alembic commands ###
