"""add video_duration_pref to users

Revision ID: b0d35c2ba291
Revises: 87e49b3b86db
Create Date: 2026-02-28 17:56:43.656700
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b0d35c2ba291'
down_revision: Union[str, None] = '87e49b3b86db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('video_duration_pref', sa.String(length=10), server_default='medium', nullable=False))
    op.drop_index('ix_users_abelian_address_hash', table_name='users', postgresql_using='hash')
    op.drop_index('uq_users_abelian_address', table_name='users', postgresql_where='(abelian_address IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_users_abelian_address', 'users', [sa.text('md5(abelian_address)')], unique=True, postgresql_where='(abelian_address IS NOT NULL)')
    op.create_index('ix_users_abelian_address_hash', 'users', ['abelian_address'], unique=False, postgresql_using='hash')
    op.drop_column('users', 'video_duration_pref')
    # ### end Alembic commands ###
